language: rust
rust:
  - nightly

cache:
  - cargo
  - directories:
      - $TRAVIS_BUILD_DIR/atdf2svd/

addons:
  apt:
    packages:
      - python3-pip
      - python3-dev

env:
  matrix:
    - CHIP=atmega1280
    - CHIP=atmega8
    - CHIP=atmega328p
    - CHIP=atmega32u4
    - CHIP=attiny85
    # Check building two together
    - CHIP=atmega32u4,attiny85
    # Check building all at once
    - CHIP=atmega1280,atmega8,atmega328p,atmega32u4,attiny85

install:
  - rustup component add rustfmt
  - cargo install form || true
  - cargo install svd2rust || true
  - test -f atdf2svd/Cargo.toml || git clone https://github.com/Rahix/atdf2svd
  - (cd atdf2svd/ && cargo install --path . || true)
  - python3 -c "__import__('yaml')" || pip3 install --user pyyaml

script:
  - make
  - echo $CHIP
  - cargo build --features $CHIP
