language: rust
rust:
  - nightly-2020-07-12

cache:
  - cargo
  - directories:
      - $TRAVIS_BUILD_DIR/atdf2svd/

addons:
  apt:
    packages:
      - python3-pip
      - python3-dev

env:
  matrix:
    - CHIP=atmega1280
    - CHIP=atmega8
    - CHIP=atmega328p
    - CHIP=atmega32u4
    - CHIP=attiny85
    # Check building all at once
    - CHIP=atmega1280,atmega8,atmega328p,atmega32u4,attiny85
    # Check building rt
    - CHIP=atmega32u4,attiny85,rt

install:
  - rustup component add rustfmt
  - cargo install form || true
  - cargo install svd2rust || true
  - cargo install atdf2svd || true
  - python3 -c "__import__('yaml')" || pip3 install --user pyyaml

script:
  - make RUSTUP_TOOLCHAIN=nightly-2020-07-12
  - echo $CHIP
  - cargo build --features $CHIP
